object FrmTelaPrincipal: TFrmTelaPrincipal
  Left = 0
  Top = 0
  Caption = 'TFrmTelaPrincipal'
  ClientHeight = 698
  ClientWidth = 1197
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  Position = poDesigned
  TextHeight = 15
  object jpnlPrincipal: TJvPanel
    Left = 257
    Top = 57
    Width = 940
    Height = 623
    Margins.Left = 0
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 0
    object jpnl_Conteudo: TJvPanel
      Left = 0
      Top = 0
      Width = 940
      Height = 623
      Align = alClient
      Color = clSilver
      ParentBackground = False
      TabOrder = 0
    end
  end
  object jpnlMenuLateral: TJvPanel
    Left = 0
    Top = 57
    Width = 257
    Height = 623
    Margins.Left = 0
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    FlatBorder = True
    FlatBorderColor = 9992033
    Align = alLeft
    BiDiMode = bdLeftToRight
    ParentBiDiMode = False
    BevelEdges = []
    BevelOuter = bvNone
    BorderWidth = 1
    Color = 13347482
    ParentBackground = False
    TabOrder = 1
    object jpnlInfo: TJvPanel
      Left = 1
      Top = 1
      Width = 255
      Height = 86
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      FlatBorderColor = clCaptionText
      Align = alTop
      BiDiMode = bdLeftToRight
      ParentBiDiMode = False
      BevelEdges = []
      BevelOuter = bvNone
      Color = 13347482
      ParentBackground = False
      TabOrder = 0
    end
    object btnProjetos: TJvBitBtn
      Left = 13
      Top = 151
      Width = 228
      Height = 66
      Caption = 'Projetos'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      OnClick = btnProjetosClick
    end
    object btnColaboradores: TJvBitBtn
      Left = 13
      Top = 56
      Width = 228
      Height = 65
      Caption = 'Colaboradores'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      Layout = blGlyphBottom
      ParentFont = False
      TabOrder = 2
      OnClick = btnColaboradoresClick
    end
    object btnTarefas: TJvBitBtn
      Left = 13
      Top = 247
      Width = 228
      Height = 66
      Caption = 'Tarefas'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      OnClick = btnTarefasClick
    end
  end
  object jpnlTopo: TJvPanel
    Left = 0
    Top = 0
    Width = 1197
    Height = 57
    FlatBorder = True
    FlatBorderColor = 9992033
    Align = alTop
    BevelOuter = bvNone
    BorderWidth = 1
    Color = 10841940
    ParentBackground = False
    TabOrder = 2
    object lblInfo: TJvLabel
      AlignWithMargins = True
      Left = 13
      Top = 13
      Width = 324
      Height = 40
      Margins.Left = 12
      Margins.Top = 12
      Align = alLeft
      Caption = 'Gerenciador de Projetos'
      Color = clWhite
      Font.Charset = ANSI_CHARSET
      Font.Color = clMenu
      Font.Height = -24
      Font.Name = 'JetBrains Mono NL'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      Transparent = True
      HotTrackFont.Charset = ANSI_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -24
      HotTrackFont.Name = 'JetBrains Mono NL'
      HotTrackFont.Style = []
      ExplicitHeight = 31
    end
  end
  object JvPanel1: TJvPanel
    Left = 0
    Top = 680
    Width = 1197
    Height = 18
    Align = alBottom
    Color = 14666685
    ParentBackground = False
    TabOrder = 3
  end
end
